"""Fictional text the synthetic corpus is assembled from.

This module holds only content: invented companies and the Markdown templates for each section of
an annual-report-style document. ``gen_synthetic_corpus.py`` holds the logic that draws figures,
fills these templates, and writes files. The split keeps both modules small (AGENTS.md) and makes
the boundary obvious: change prose here, change behavior there.

Every name, place, segment, and risk below is invented. Tickers end in ``.TEST`` so they cannot be
read as listed symbols, and contact placeholders use the reserved ``example.com`` domain and the
``555-01xx`` telephone block set aside for fiction.

Templates are ``str.format`` strings; ``gen_synthetic_corpus._document_values`` supplies every key.
Paragraphs are re-wrapped when rendered, so the line breaks here do not reach the output. Blocks
beginning with ``|``, ``-``, ``#``, or ``>`` are emitted verbatim, which is how tables, list items,
and risk subheadings survive.
"""

from __future__ import annotations

from dataclasses import dataclass

GENERATOR_PATH = "scripts/gen_synthetic_corpus.py"
PLACEHOLDER_DOMAIN = "example.com"

DISCLAIMER = (
    f"Fictional company and invented figures. Generated by {GENERATOR_PATH}."
    " Not real financial data and not investment advice."
)

# The first body line of every document. Kept on one line so a reader, a diff, and a test all see
# the whole warning without unwrapping anything.
BANNER = (
    "> **SYNTHETIC DOCUMENT - NOT REAL FINANCIAL DATA.** {company} is a fictional company, and every"
    " figure, name, address, and statement below is invented sample data written by"
    f" `{GENERATOR_PATH}` to exercise Quorum's ingestion pipeline. Nothing here is a real filing or"
    " a real metric, and nothing here is investment advice."
)

FRONT_MATTER = """\
---
title: "{company} Annual Report (SYNTHETIC) - Fiscal Year {fiscal_year}"
synthetic: true
disclaimer: "{disclaimer}"
company: "{company}"
ticker: "{ticker}"
form: "{form}"
fiscal_year: {fiscal_year}
generator: "{generator}"
seed: {seed}
---"""

TITLE = "# {company} - Annual Report ({form}, SYNTHETIC), Fiscal Year {fiscal_year}"

HEADWINDS: tuple[str, ...] = (
    "higher labour cost per unit",
    "an unfavourable segment mix",
    "maintenance spending phased into the second half",
    "softer volumes in the fourth quarter",
)

STREET_NAMES: tuple[str, ...] = ("Harbour Way", "Kestrel Lane", "Foundry Road", "Alder Terrace")


@dataclass(frozen=True)
class CompanyProfile:
    """A fictional issuer the generator writes filings for.

    Attributes:
        name: Invented company name, used in headings and front matter.
        ticker: Invented ticker; always ends in ``.TEST`` so it cannot be a listed symbol.
        slug: Uppercase filename fragment identifying the company.
        industry: One-line description of the invented business.
        headquarters: Invented place name for the registered office.
        segments: Reportable segment names; each gets a revenue line in the segment table.
        growth_drivers: Candidate explanations the narrative attributes revenue movement to.
        risks: Company-specific risk factors, as ``###`` subsections.
    """

    name: str
    ticker: str
    slug: str
    industry: str
    headquarters: str
    segments: tuple[str, ...]
    growth_drivers: tuple[str, ...]
    risks: str


FREIGHT_RISKS = """\
### Fuel and Energy Price Volatility

Diesel and electricity are the largest variable inputs in the invented cost base described here.
Contracted fuel surcharges reset quarterly, so a sharp move in energy prices would be absorbed for a
quarter before it could be passed through, compressing margin in the interim.

### Contract Concentration

The ten largest contracts account for a majority of segment revenue in this sample data. Losing one
at renewal, or repricing it downward, would move reported results out of proportion to the volume
involved.

### Network Capacity and Labour Availability

Terminal throughput depends on licensed drivers and yard staff being available where the freight is.
Sustained wage inflation or a shortage of qualified operators would raise the cost of serving
existing volumes and delay the invented expansion described above."""

GRID_RISKS = """\
### Rate Case Outcomes

Allowed returns under the invented regulatory regime described here reset on a multi-year cycle. A
determination below the assumed allowed return would reduce revenue in the regulated segment with no
matching reduction in the obligation to keep investing.

### Storm and Physical Asset Exposure

Overhead distribution assets are exposed to severe weather. Restoration cost is recoverable only in
part and only after review, so a severe season would open a timing gap between the spending and its
recovery.

### Interconnection Backlog

Growth in grid services depends on connecting new generation to the network. Permitting delays or
long equipment lead times would push revenue into later periods even where contracts are signed."""

INSTRUMENT_RISKS = """\
### Instrument Placement Cycles

Instrument revenue is lumpy because laboratory capital budgets are approved annually. Deferring
placements into the following year would depress instrument revenue even when the installed base and
consumables demand are unchanged.

### Single-Source Components

Several assemblies in this invented product line are sourced from a single qualified supplier.
Requalifying an alternative takes multiple quarters, so an interruption would constrain output well
beyond the interruption itself.

### Regulatory Clearance Timelines

Selling into clinical settings depends on clearances from health regulators. A review longer than
the one assumed in these invented plans would delay launches and shift the revenue attached to them
into later fiscal years."""

PROFILES: tuple[CompanyProfile, ...] = (
    CompanyProfile(
        name="Meridian Freight Systems",
        ticker="ZZMFS.TEST",
        slug="MERIDIAN-FREIGHT",
        industry="intermodal freight, contract warehousing, and last-mile delivery",
        headquarters="Port Calder, Alderran",
        segments=("Intermodal Transport", "Contract Warehousing", "Last-Mile Delivery"),
        growth_drivers=(
            "higher contracted intermodal volumes on the northern corridor",
            "a full year of operation at the Redgate distribution centre",
            "warehousing contracts renewed at higher rates",
        ),
        risks=FREIGHT_RISKS,
    ),
    CompanyProfile(
        name="Halcyon Grid Utilities",
        ticker="ZZHGU.TEST",
        slug="HALCYON-GRID",
        industry="regulated electricity distribution, grid services, and renewable generation",
        headquarters="Wexbury, Alderran",
        segments=("Regulated Distribution", "Grid Services", "Renewable Generation"),
        growth_drivers=(
            "a scheduled tariff step-up in the regulated distribution segment",
            "the first full year of the Cobbet Ridge storage programme",
            "higher connection volumes from distributed generation",
        ),
        risks=GRID_RISKS,
    ),
    CompanyProfile(
        name="Vantor Clinical Instruments",
        ticker="ZZVCI.TEST",
        slug="VANTOR-INSTRUMENTS",
        industry="laboratory instruments, consumables, and service contracts",
        headquarters="Ellisfield, Northmark",
        segments=("Analytical Instruments", "Consumables and Reagents", "Service Contracts"),
        growth_drivers=(
            "higher placements of the invented VX-40 analyser platform",
            "an expanding installed base pulling through consumables",
            "multi-year service agreements renewed at higher attachment rates",
        ),
        risks=INSTRUMENT_RISKS,
    ),
)

OVERVIEW = """\
{company} is a fictional {industry} business, invented for Quorum's sample corpus. It is described
as reporting from a head office in {headquarters} through {segment_count} segments:
{segment_list}. In this invented history it serves {accounts} contracted accounts from {locations}
service locations, staffed by {employees} full-time equivalents against {prior_employees} a year
earlier.

About {contracted_pct} percent of fiscal {fiscal_year} revenue came from multi-year agreements with
scheduled price escalators, and the rest from spot and short-cycle work. Renewals are staggered
through the year so that no single quarter carries an outsized share of the renewal book.

None of the entities, places, contracts, or amounts described in this document exist. They are
written to give an ingestion pipeline realistically shaped text to parse, chunk, redact, and cite."""

FINANCIALS = """\
Amounts are stated in millions of United States dollars unless noted otherwise. Every figure is
invented sample data for a company that does not exist: no amount corresponds to any real issuer,
period, or transaction, and the comparatives are invented alongside the current year rather than
taken from anywhere.

{financial_table}"""

SEGMENT_RESULTS = """\
Segment revenue is reported before intersegment eliminations, which are nil in this invented
presentation, so the segment lines sum to total revenue.

{segment_table}

{lead_segment} is the largest segment at ${lead_revenue} million, or {lead_share} percent of the
total. Segment shares in this sample data move only gradually, because the contract book reprices on
multi-year cycles rather than annually."""

DISCUSSION = """\
Revenue for fiscal {fiscal_year} was ${revenue} million, against ${prior_revenue} million in fiscal
{prior_year}, a change of {revenue_change}. Management attributes the movement mainly to {driver},
partly offset by {headwind}.

Gross margin was {gross_margin} percent against {prior_gross_margin} percent in the prior year, a
move of {gross_margin_points}. Operating margin of {operating_margin} percent reflects the same mix
effects together with the fixed cost of the service network, which does not flex with volume inside
a single reporting period.

Cash from operations of ${operating_cash_flow} million covered capital expenditure of ${capex}
million, equal to {capex_pct} percent of revenue, leaving free cash flow of ${fcf} million.
Contracted backlog closed the year at ${backlog} million, or
{backlog_pct} percent of fiscal {fiscal_year} revenue; management treats that ratio as the leading
indicator for the following year in this invented planning model."""

RISK_FACTORS = """\
The risks below are invented for this sample document. They describe how a business of this shape
could plausibly fail to meet the plans stated above; they are not warnings about any real company,
and they are not ranked by likelihood.

{company_risks}

### Cybersecurity and Data Integrity

The systems described here process contract, billing, and operational records. An intrusion or a
data integrity failure would interrupt service, trigger notification obligations, and require
remediation spending that the invented figures above do not budget for.

### Regulatory and Reporting Change

Changes to disclosure, environmental, or tax rules would raise compliance cost and could require
comparative figures to be restated. Every amount in this document assumes the rules in force at the
fictional reporting date."""

LIQUIDITY = """\
The Company closed fiscal {fiscal_year} with ${cash} million of cash and equivalents and an undrawn
revolving credit facility of ${revolver} million. Net debt to adjusted operating earnings was
{leverage} times, inside the invented covenant ceiling assumed throughout this document.

Capital allocation priorities in this fictional plan are, in order: maintenance capital expenditure,
contracted growth capital already underwritten by customer commitments, debt reduction toward the
target leverage band, and only then discretionary returns. No dividend is assumed and no share
repurchase authorisation is described.

Scheduled maturities are laddered so that no single year carries more than a third of gross
borrowings. Liquidity headroom, defined here as cash plus the undrawn facility, was ${headroom}
million at the fiscal {fiscal_year} year end."""

FORWARD_LOOKING = """\
Statements in this document that describe expectations, plans, targets, or outcomes are
forward-looking in form. They are also entirely fictional: they describe a company that does not
exist, written from a seeded random number generator.

In a real filing such statements would carry risks and uncertainties that could cause actual results
to differ, and the issuer would disclaim any obligation to update them. That shape is reproduced
here only so the sample corpus carries the sections a real annual report carries. Fiscal
{fiscal_year} figures in this document must never be quoted as fact, cited as evidence about any
company, or used as investment advice."""

CONTACT = f"""\
The contact details below are placeholders from reserved ranges: addresses use the
{PLACEHOLDER_DOMAIN} domain and telephone numbers the 555-01xx block set aside for fiction. They are
here so the ingest-time redactor has realistic material to detect and replace.

- Registered office (fictional): {{street}}, {{headquarters}}
- Investor relations: {{email}}
- Media enquiries: {{media_email}}
- Telephone: {{phone}}
- Ticker (fictional, not a listed symbol): {{ticker}}"""

SECTIONS: tuple[tuple[str, str], ...] = (
    ("Business Overview", OVERVIEW),
    ("Selected Financial Data", FINANCIALS),
    ("Segment Results", SEGMENT_RESULTS),
    ("Management Discussion and Analysis", DISCUSSION),
    ("Risk Factors", RISK_FACTORS),
    ("Liquidity and Capital Resources", LIQUIDITY),
    ("Forward-Looking Statements", FORWARD_LOOKING),
    ("Investor Relations Contact", CONTACT),
)
